public with sharing class AssetConstants {
    // Asset Request Status Constants
    public static final String REQUEST_STATUS_PENDING = 'Pending';
    public static final String REQUEST_STATUS_APPROVED = 'Approved';
    public static final String REQUEST_STATUS_REJECTED = 'Rejected';

    
    // Asset Status Constants
    public static final String ASSET_STATUS_AVAILABLE = 'Available';
    public static final String ASSET_STATUS_ALLOCATED = 'Allocated';
    public static final String ASSET_STATUS_ASSIGNED = 'Assigned';
    
    // Employee Status Constants
    public static final String EMPLOYEE_STATUS_ACTIVE = 'Active';
    public static final String EMPLOYEE_STATUS_INACTIVE = 'Inactive';
}